# Generated by Django 5.1 on 2024-08-15 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_address_user_age_user_birth_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
    ]
